### ISSUE TITLE
Song upload

### ISSUE THREAD

**Issue by weiquany** [weiquany/KTVAnywhere#14]
A feature for users to upload their music tracks to the application.

## User story
As a user, 
* I want to be able to select songs to add to the application.
* I want to give details about the song (song name, artists).
* I want to select lyrics for the song.
### Acceptance criteria
The application should:
- [x] Allow users to select songs from their disk to upload
- [x] Allow users to select lyrics from their disk to upload
- [x] Allow users to input song details about the song
- [x] Prevent upload if no song file is selected
- [x] Prevent upload if no song name is specified
## Complexities
* File picker to choose song and lyrics

**Comment by malwaregarry** [comment]
implemented song upload,
left with: delete song and edit song
