### ISSUE TITLE
Display for lyrics

### ISSUE THREAD

**Issue by weiquany** [weiquany/KTVAnywhere#15]
Introduce a display for lyrics to be shown.

## User story
As a user, 
* I want to see the lyrics as the song is playing.
* I want to be able to toggle the lyrics.
### Acceptance criteria
The application should:
- [x] Load the correct lyrics file from disk
- [x] Display lyrics in sync with the song
- [x] Allow users to toggle display of lyrics
## Complexities
* Loading of text file
* Display based on specified timestamps
* Difficulty in automating test

**Comment by malwaregarry** [comment]
Implemented in: 430dd85a18e19508c7ea327b2ad48f49f01904aa and 44eb438e5e92ee38efc971a04501d808025a8235
