### ISSUE TITLE
Song library

### ISSUE THREAD

**Issue by weiquany** [weiquany/KTVAnywhere#16]
A library of songs that can be managed.

## User story
As a user, 
* I want to view all songs I uploaded to the application.
* I want to see all the relevant details about songs.
* I want to be able to delete songs I no longer want.
* I want to be able to edit details about songs previously uploaded.
### Acceptance criteria
The application should:
- [x] Display a list of uploaded songs
- [x] Show details about a song specified
- [x] Allow users delete songs
- [x] Allow users to edit songs
## Complexities
* None

**Comment by malwaregarry** [comment]
Created a display for song library, still working on library management

**Comment by malwaregarry** [comment]
added song edit and delete in aa19923db4a56bae53af24a1e1a9ce9ff347f3aa
